[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/shopee"
  to = "/.netlify/functions/shopee"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/sync"
  to = "/.netlify/functions/sync"
  status = 200

[[redirects]]
  from = "/api/query"
  to = "/.netlify/functions/query"
  status = 200
